# Mobile App Test Labels
HOT_WATER_LABEL = "Hot Water"
CANCEL_HOT_WATER_LABEL = "Tap to Cancel Hot Water"
CANCEL_BREW_LABEL = "Tap to Cancel Brew"
CANCEL_HOT_WATER_BUTTON = "Canceling  Hot Water..."
BREW_CANCELED_LABEL = "Brew Canceled"
FIRST_NAME = "John"
LAST_NAME = "Doe"
EMAIL_PLACEHOLDER = "user<UniqueValue>@gmail.com"
PWD_PLACEHOLDER = "<UniquePasswordValue>"
POD_RECOG_TITLE = "Peet's Coffee™"
POD_RECOG_VARIETY = "Brazil Minas Naturais"
